config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: postgres
      host: 0.0.0.0
      pass: password
      port: 3005
      schema: public
      threads: 8
      type: postgres
      user: airbyte
  target: prod
